name: CI-ESP8266

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -U platformio
        platformio update

    - name: Test with pytest
      run: |
        python --version
        platformio run
    
    - run: mkdir -p output 
    - run: cp  .pio/build/nodemcuv2/*.bin .pio/build/nodemcuv2/*.elf output
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: output
